### ISSUE TITLE
Create a Participant Portal for managing consents

### ISSUE THREAD

**Issue by sh-ura** [dycons/participant-portal#3]
As a participant, I should be able to review and edit my consent information. I should be able to login to the Participant Portal, see my default and project consents be loaded onto my homepage, edit any consent(s) and have them be kept up-to-date with my edits. I should be able to log out of the portal and trust that my session is fully terminated, such that other users of my computer (or other websites) are unable to access any of my DyCons-related data.

### Acceptance Criteria

- The Participant IdP and Participant Portal can be launched **together** by running `docker-compose up`
- Any host-specific environment variables, arguments, or paths are called into docker-compose from a `.env` file. A sample `default.env` file is provided in the repository root.
- On a `Log In` page, the user is prompted to authenticate with the Participant IdP via an interface on the Participant Portal.
- The Participant Portal holds on to the authenticated user's JWT until the user terminates their session, at which point the JWT is safely discarded.
- The user is able to terminate their session by clicking a `Log Out` UI element. Upon being logged out, the user is redirected to the `Log In` page. Any cached information about the user is discarded upon `Log Out`.
- The authenticated user's `Home Page` contains elements for displaying `Default Consents` and `Project Consents`, with the data schemas outlined below.
- Consents can be edited, with a clear "Submit changes" button that refreshes the `Home Page` and displays the updated information. The editing view is accompanied by the following text: "Beginning within 24 hours of submitting the changes, changes in data-sharing consents will be applied to all future queries on your data. Changes in data-sharing consents cannot be applied to past queries."

### Consents Data Schema

**Default Consents (1):**

_Default consents to sharing data with new projects_
| Type of health data | Automatically share this data with newly approved Projects? |
|---------------------|-------------------------------------------------------------|
| Clinical            | oneOf(Yes, No)                                          |
| Genetic             | oneOf(Yes, No)                                          |

**Project Consents (0..*):**

_Project {{project_name}}: Consents to sharing data_
| Type of health data | Share this data with the {{project_name}} Project? |
|---------------------|----------------------------------------------------|
| Clinical            | oneOf(Yes, No)                                     |
| Genetic             | oneOf(Yes, No)                                     |

### Portal Interface

The full description of the Participant Portal GUI can be reviewed [here](https://docs.google.com/document/d/1u_vjsbsghJNKv27AfkJjumOUX80B-IlmzSu2eKaP6ps/edit#heading=h.gpajrpmwnozg).

### Sequence Diagram

The participant consent-change sequence diagram can be reviewed [here](https://github.com/dycons/design/blob/develop/demo1/diagrams/participant_consent_change.md).

**Comment by yuriy-pavlov** [comment]
WON'T DO
Closing due to repo archival.
